name: detect-workflow 
on:
  push:
    branches:
      - master
      - main 

jobs:
  detect-changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.filter.outputs.changes }}
    steps:
    - name: get the code 
      uses: actions/checkout@v3
    - name: detect the changes 
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters:  'backend/**'
        list-files: "json"
  render:
    name: Render
    runs-on: ubuntu-latest
    needs:
    - detect-changes
    strategy:
      fail-fast: false
      matrix:
        env: ${{ fromJSON(needs.detect-changes.outputs.env) }}
    steps:
    - name: print greeting 
      uses: echo "hello-world" 
      
   
